import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import SupabaseProvider from "@/context/SupabaseProvider";
import StoreProvider from "./StoreProvider";
import { Toaster } from "sonner";
import { ClientProviders } from "@/app/ClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "A Ecommerce Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="light"
      style={{ colorScheme: "light" }}
    >
      <body className={inter.className}>
        <SupabaseProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <StoreProvider>
              <ClientProviders>
                <Navbar />
                {children}
              </ClientProviders>
            </StoreProvider>
            <Toaster position="top-center" richColors />
          </ThemeProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
